name: Create A Pre-release

on:
  push:
    branches:
      - pre-release
    tags:
    - 'v*'
    
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:

      - name: Setup Action
        uses: actions/checkout@v1

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: true
